# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hp/Desktop/FPGA/CPU/AKD_T/AKD_T3/AKD_T3/AKD_T3.srcs/sources_1/ip/IM_entire/IM_entire.xci
# IP: The module: 'IM_entire' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Desktop/FPGA/CPU/AKD_T/AKD_T3/AKD_T3/AKD_T3.gen/sources_1/ip/IM_entire/IM_entire_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IM_entire'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/hp/Desktop/FPGA/CPU/AKD_T/AKD_T3/AKD_T3/AKD_T3.srcs/sources_1/ip/IM_entire/IM_entire.xci
# IP: The module: 'IM_entire' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hp/Desktop/FPGA/CPU/AKD_T/AKD_T3/AKD_T3/AKD_T3.gen/sources_1/ip/IM_entire/IM_entire_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IM_entire'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
